### ISSUE TITLE
CUDA Out Of Memory Errors

### ISSUE THREAD

**Issue by nberlette** [LeafYeeXYZ/PainterLeaf#9]
Hello, nice work here.

I'm running into some memory management issues when using this, however. It's not happening on every single run, and I haven't identified any pattern that causes it yet, so currently it remains an intermittent error. But I've run into it 4 times now, out of a total of 14 generation runs.

Here's the error text that appears in the modal dialog:

```
生成失败
服务端返回错误信息: {"error":"unknown error","warnings":["CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 14.75 GiB total capacity; 8.46 GiB already allocated; 985.06 MiB free; 8.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF","There was an inference error: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 14.75 GiB total capacity; 8.46 GiB already allocated; 985.06 MiB free; 8.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"]}
```

🤷🏼‍♀️

**Comment by LeafYeeXYZ** [comment]
Thanks for your feedback! 

It's due to the limits of the free Hugging Face Inference API. Especially when the prompt is too long.

You may try another model instead.
